var first_name = 'Angel';
var last_name ='Leu';
var age = 24;
var dateOfBirth = '08/16/1995';
var address = '422 Richard st.';
console.log(first_name);
console.log(last_name);
console.log(age);
console.log(dateOfBirth);
console.log(address);